name: pokeapi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4
dependency_overrides:
  collection: ^1.19.1
  path: ^1.9.1
dependencies:
  flutter:
    sdk: flutter
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_cors_headers:  ^0.1.5
  postgres: ^3.4.4
  mime: ^2.0.0
  http_parser: ^4.1.1
  image_picker: ^1.1.2
  http: ^1.2.2
  webview_flutter: ^4.10.0
  shelf_swagger_ui: ^1.0.0+2
  yaml: ^3.1.2
  flutter_dotenv: ^5.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env